### ISSUE TITLE
issue about the "lg.fc" meanning in the results of called peaks

### ISSUE THREAD

**Issue by SoManyPepople** [ZhenxingGuo0015/TRES#3]
Hi, Dr. Guo,
I'm a postdoc from Suchow. These days, I am using TRESS to call m6A peaks for our human MeRIP-seq data. I planned to call peaks for each sample seperately. I try to call peaks via the wrapped 'TRESS_peak' function and 'DivideBins' + 'CallPeaks.oneRep' (with default options), their results are identifical.  I got  confused about the last column 'lg.fc' of the output. 
For example, I got 23458 peaks from one sample (named "Middle_1"), and their 'lg.fc' values were ranging from 0.054 to 1.43 .
str(allPeaks_sf)
'data.frame':   23458 obs. of  10 variables:
 $ chr               : chr  "chr7" "chr9" "chr4" "chr12" ...
 $ start             : num  1.02e+08 1.28e+08 1.25e+08 6.73e+07 6.53e+07 ...
 $ end               : num  1.02e+08 1.28e+08 1.25e+08 6.73e+07 6.53e+07 ...
 $ strand            : chr  "+" "-" "-" "+" ...
 $ summit            : num  1.02e+08 1.28e+08 1.25e+08 6.73e+07 6.53e+07 ...
 $ Middle_1_input.bam: num  759 3064 1199 1932 1540 ...
 $ Middle_1_RIP.bam  : num  10397 27355 9821 9503 12419 ...
 $ pvals             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ p.adj             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ lg.fc             : num  1.43 1.39 1.37 1.36 1.33 ...
> summary(allPeaks_sf$lg.fc)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.05407 0.24781 0.35832 0.39189 0.50287 1.43103

I manually calculated enrichment fold for the first peak and the last peak, but found their corresponding enrichment fold should be: 10397/1.199/759 = 11.42, and  102/1.199/3 = 28.35696
> sf
Middle_1_input.bam   Middle_1_RIP.bam
          1.000000           1.199738
> allPeaks_sf[23458,]
        chr    start      end strand   summit Middle_1_input.bam
18055 chr17 44006072 44006221      + 44006096                  3
      Middle_1_RIP.bam pvals p.adj      lg.fc
18055              102     0     0 0.05406714

Hence, I am not sure what is the calculation of the 'lg.fc' values. Could please provide more details about that?

**Comment by ZhenxingGuo0015** [comment]
Hi,

Thank you for trying our MeRIP-seq peak calling package TRESS.

TRESS calculates lg.fc as 
```{r}
    lfc = log((IP.count/IP.sf + c0)/(Input.count/Input.sf + c0))
```
where  c0 is a pseudo-count calculated using the mean of both IP and Input count from that sample:
```{r}
c0 = mean(cbind(Input.count, IP.count), na.rm = TRUE)
```
The reason why the "lg.fc" from TRESS differs from what you obtained may be because of this "c0".

In addition, in our origin functions ``TRESS_peak()" and "CallPeaks.oneRep()", we forgot to filter peaks using "lfc" and "fdr" for one replicate scenario. That's why you obtained peaks with lower "lfc" under default settings. I just corrected to only output peaks satisfying the threshold specified by ``WhichThreshold'' in both``TRESS_peak()" and ``CallPeaks.oneRep()". The new version of TRESS (1.1.6) should be available to download soon.

Another thing I would like to mention is that, please include all replicates if you have multiples. Peaks called with multiple replicates would be more robust and stable as they were identified after accounting for the variation across replicates.


Please let me know if you have any other questions/problems in using TRESS.

Best,
Zhenxing

**Comment by ZhenxingGuo0015** [comment]
> Hi, Dr. Guo, I'm a postdoc from Suchow. These days, I am using TRESS to call m6A peaks for our human MeRIP-seq data. I planned to call peaks for each sample seperately. I try to call peaks via the wrapped 'TRESS_peak' function and 'DivideBins' + 'CallPeaks.oneRep' (with default options), their results are identifical. I got confused about the last column 'lg.fc' of the output. For example, I got 23458 peaks from one sample (named "Middle_1"), and their 'lg.fc' values were ranging from 0.054 to 1.43 . str(allPeaks_sf) 'data.frame': 23458 obs. of 10 variables: $ chr : chr "chr7" "chr9" "chr4" "chr12" ... $ start : num 1.02e+08 1.28e+08 1.25e+08 6.73e+07 6.53e+07 ... $ end : num 1.02e+08 1.28e+08 1.25e+08 6.73e+07 6.53e+07 ... $ strand : chr "+" "-" "-" "+" ... $ summit : num 1.02e+08 1.28e+08 1.25e+08 6.73e+07 6.53e+07 ... $ Middle_1_input.bam: num 759 3064 1199 1932 1540 ... $ Middle_1_RIP.bam : num 10397 27355 9821 9503 12419 ... $ pvals : num 0 0 0 0 0 0 0 0 0 0 ... $ p.adj : num 0 0 0 0 0 0 0 0 0 0 ... $ lg.fc : num 1.43 1.39 1.37 1.36 1.33 ...
> 
> > summary(allPeaks_sf$lg.fc)
> > Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
> > 0.05407 0.24781 0.35832 0.39189 0.50287 1.43103
> 
> I manually calculated enrichment fold for the first peak and the last peak, but found their corresponding enrichment fold should be: 10397/1.199/759 = 11.42, and 102/1.199/3 = 28.35696
> 
> > sf
> > Middle_1_input.bam   Middle_1_RIP.bam
> > 1.000000           1.199738
> > allPeaks_sf[23458,]
> > chr    start      end strand   summit Middle_1_input.bam
> > 18055 chr17 44006072 44006221      + 44006096                  3
> > Middle_1_RIP.bam pvals p.adj      lg.fc
> > 18055              102     0     0 0.05406714
> 
> Hence, I am not sure what is the calculation of the 'lg.fc' values. Could please provide more details about that?

**Comment by SoManyPepople** [comment]
Very grateful for your kind reply. Your advice are very helpful. 
Happy new year! 虎年大吉！

**Comment by ZhenxingGuo0015** [comment]
Hi,

Gold to help. Happy new year!


Best,
Zhenxing

From: SoManyPepople ***@***.***>
Reply-To: ZhenxingGuo0015/TRES ***@***.***>
Date: Saturday, January 22, 2022 at 7:47 PM
To: ZhenxingGuo0015/TRES ***@***.***>
Cc: "Guo, Zhenxing" ***@***.***>, State change ***@***.***>
Subject: [External] Re: [ZhenxingGuo0015/TRES] issue about the "lg.fc" meanning in the results of called peaks (Issue #3)


Very grateful for your kind reply. Your advice are very helpful.
Happy new year! 虎年大吉！

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZhenxingGuo0015%2FTRES%2Fissues%2F3%23issuecomment-1019385816&data=04%7C01%7Czhenxing.guo%40emory.edu%7Cda20be6a97ea4e03f20408d9de09e23f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637784956314789805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ST%2B9MQbrwFVOEJ73XZSA0qkoq8eAaBJ6VO%2F3mEggJwI%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOBLLSZYABDRIBXLS6JDITDUXNFYXANCNFSM5MJLSIDA&data=04%7C01%7Czhenxing.guo%40emory.edu%7Cda20be6a97ea4e03f20408d9de09e23f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637784956314789805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2m885PB2lX7C5enVJiCM2a8yqnbe3P2V2XlvSVihEAE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Czhenxing.guo%40emory.edu%7Cda20be6a97ea4e03f20408d9de09e23f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637784956314789805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q%2BNELNfQmuYVGFmHuhfICpJCJtamFuy6PmP5e9QMdYg%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Czhenxing.guo%40emory.edu%7Cda20be6a97ea4e03f20408d9de09e23f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637784956314789805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FyiZAsAPOyx4ptTGueYy3fWiCwOKPap156wI2GamB%2B0%3D&reserved=0>.
